# Generated by Django 4.0.3 on 2022-04-01 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologies',
            name='question_mark',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_questions',
            name='option1',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_questions',
            name='option2',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_questions',
            name='option3',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_questions',
            name='option4',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
