# Generated by Django 4.0.3 on 2022-04-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0002_technologies_question_mark_test_questions_option1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_questions',
            old_name='user_id',
            new_name='technology_id',
        ),
    ]
