# Generated by Django 4.0.3 on 2022-03-22 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('experience_level', models.CharField(max_length=150)),
                ('companies_experience', models.CharField(max_length=255)),
                ('year_of_exp', models.IntegerField(null=True)),
                ('current_ctc', models.CharField(max_length=255)),
                ('expected_ctc', models.CharField(max_length=255)),
                ('notice_period_from', models.DateField(null=True)),
                ('notice_period_to', models.DateField(null=True)),
                ('willingtowork_shifts', models.CharField(max_length=50)),
                ('willingtowork_contract', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=1024)),
                ('primary_skill', models.CharField(max_length=150)),
                ('secondary_skill', models.CharField(max_length=150)),
                ('other_skill', models.CharField(max_length=150)),
                ('primary_skill_rating', models.IntegerField(null=True)),
                ('secondary_skill_rating', models.IntegerField(null=True)),
                ('other_skill_rating', models.IntegerField(null=True)),
                ('certification', models.CharField(max_length=255)),
                ('agreement', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
