# Generated by Django 4.0.3 on 2022-03-22 17:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('jobs_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=155)),
                ('min_experience', models.IntegerField(blank=True, null=True)),
                ('max_experience', models.IntegerField(blank=True, null=True)),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('max_salary', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=155)),
                ('certification', models.CharField(max_length=155)),
                ('discription', models.CharField(max_length=255)),
                ('vacancies_no', models.IntegerField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('address', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Make sure you enter a valid phone number', regex='^\\d{10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Test_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.jobs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applications_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.applications')),
                ('candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
                ('schedule_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.test_schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=100)),
                ('candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.test')),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='recruiter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiter'),
        ),
        migrations.CreateModel(
            name='Certification_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_content', models.CharField(max_length=1024, null=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
                ('score_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.score')),
            ],
        ),
        migrations.AddField(
            model_name='applications',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.jobs'),
        ),
    ]
